name: 'Prettier Check'
author: 'Rutaj Dash'
description: 'A simple action which runs the Prettier CLI Check'
inputs:
  file_pattern:
    description: 'The file pattern to scan'
    required: false
    default: '**/*.js'
  config_path:
    description: 'The path to the prettierrc file'
    required: false
    default: ''
  ignore_path:
    description: 'The path to the prettierignore file'
    required: false
    default: './.prettierignore'
  prettier_version:
    description: 'The version of prettier to install'
    required: false
    default: 'latest'
  fail_on_error:
    description: 'Whether the script should fail when linting errors are found'
    required: false
    default: true

outputs:
  prettier_output:
    description: 'The output from prettier'
    value: ${{ steps.prettier-run.outputs.prettier-output }}

runs:
  using: 'composite'
  steps:
    - name: Installing Prettier
      id: prettier-install
      shell: bash
      run: npm install --global prettier@${{ inputs.prettier_version }}

    - name: Running Prettier
      id: prettier-run
      shell: bash
      run: |
        PRETTY=$(prettier --list-different --config ${{ inputs.config_path }} --ignore-path ${{ inputs.ignore_path }} --no-error-on-unmatched-pattern ${{ inputs.file_pattern }})
        echo "prettier-output=$PRETTY" >> "$GITHUB_OUTPUT"
    - name: Fail On Error
      id: fail-on-error
      if: steps.prettier-run.outputs.prettier-output != 0 && steps.prettier-run.outputs.prettier-output != '' && inputs.fail_on_error
      shell: bash
      run: |
        echo "Found errors: "
        echo "${{ steps.prettier-run.outputs.prettier-output }}
        exit 1

branding:
  icon: 'search'
  color: 'gray-dark'
